### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by Ingvarr71** [FlokoROM/manifesto#2]
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: system/core/fastboot/Android.bp:226:52: unrecognized property "product_variables.lineage.target_uses_prebuilt_dynamic_partitions"

How to fix?

**Comment by lindwurm** [comment]
due to untracked upstream change(s).
fixed in:
* https://github.com/FlokoROM/vendor_floko/commit/b8cb5e5b05126664b0058c7ce8fee4e3008b56af
* https://github.com/FlokoROM/manifesto/commit/c9abb7b980eab23a50a8c15451ce1c7b877aabdc
