### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [FlokoROM/manifesto#4]
-including packages/apps/Matlog/Android.mk ...è[1mpackages/apps/Matlog/app/src/main/Android.mk: [31merror:[0m[1m MatLog: Specifies both LOCAL_SDK_VERSION (system_current) and LOCAL_PRIVATE_PLATFORM_APIS (true) but should specify only one [0m
In file included from build/make/core/package.mk:78:
In file included from packages/apps/Matlog/Android.mk:17:
In file included from packages/apps/Matlog/app/Android.mk:17:
In file included from packages/apps/Matlog/app/src/Android.mk:17:
In file included from packages/apps/Matlog/app/src/main/Android.mk:48:
In file included from build/make/core/package.mk:58:
In file included from build/make/core/package_internal.mk:370:
In file included from build/make/core/java.mk:173:
[1mbuild/make/core/sdk_check.mk:34: [31merror: [0m[1mdone.[0m
*makefile error

**Comment by lindwurm** [comment]
insufficient target device info
